version: '3.3'
services:
  api:
    build: ./api
    command: npm run debug
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'